# App name
spring.application.name=hostel-booking-platform

# ===== MySQL Database Config =====
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Koyna@0911
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate Config =====
# update = tables auto create/alter ho jaengi entity ke basis par (learning ke liye theek hai)
# production me isko 'validate' rakhte hain aur Flyway se migrations karte hain (baad me sikhayenge)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Server Config =====
server.port=8822

# ===== JWT Config =====
jwt.secret=hostel-booking-platform-jwt-secret-key-2026-dev-only
jwt.expiration=86400000